# Generated by Django 2.2.1 on 2019-05-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_news_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='titleexam',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
